#!/usr/bin/env python

import numpy as np
import cv2
import cv2.aruco as aruco

from cv_bridge import CvBridge, CvBridgeError

# Purpose of this node is to read raw camera images (make topic reconfigurale)
# and to output a stream of positions for each marker (just one to begin with)
 
OpenCVBridge = None

def set_up_markers_topic():
    pass

def subscribe_to_images():
    pass   

def set_up_opencv():
    global OpenCVBridge
    OpenCVBridge = CvBridge()

if __name__ == '__main__':
    print("Booting up Locate Markers Node...")
    set_up_opencv()
    set_up_markers_topic()
    subscribe_to_images()

    rospy.init_node('locate_markers', anonymous=True)
    rate = rospy.Rate(1)
    while True:
        rate.sleep()
    print("Done.")
